### ISSUE TITLE
Usage examples

### ISSUE THREAD

**Issue by phanirithvij** [anubiann00b/AnimeDownloaderWeb#1]
Please tell me how to use by some examples
For eg:
I tried

**Comment by phanirithvij** [comment]
https://anime-downloader-web.herokuapp.com/?anime=one%20piece&episode=001

**Comment by phanirithvij** [comment]
It's not working

**Comment by anubiann00b** [comment]
I made this in 2015 haha, and it was done through quite simple webpage parsing. I'm sure the website I was using then has changed, and the script would probably need significant rework to be functional again. I'm not really interested in updating this though, sorry :(
